name: Verify Docker
on: [push]

jobs:
  verify-docker:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Docker Installation
        run: |
          docker --version
          docker info
          docker run hello-world
